/**
 * The Census
 * ----------
 * David counts the people and repents; the prophet Gad offers three choices, and a plague stalks Israel until the threshing floor of Araunah. Stage: a nation of tents under a wasting sky, a king on his rooftop in grief, an altar rising on a purchased threshing floor; grey light breaking warm.
 *
 * Palette 0x1a0e08 → 0x0a0604 · light: ember · hero: altar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, column, throne, house, altar, flame, person, crowd } from './david-kit.js';

const BG = 0x1a0e08;
const GROUND = 0x040202;

export function build(group) {
    const W = createScene(group, { seed: 498069790, bg: BG, fogNear: 45, fogFar: 180 });

    /* light — ember */
    W.lights({ sky: 0x3a2418, gnd: 0x1a0e08, hemi: 0.4, sun: 0xff7a30, sunI: 0.7, sunPos: [20, 26, 30] });

    W.stars(90, 150, [0xf0e0c8, 0xd8c0a0], 0.7);
    W.disc([0, 34, -150], 14, 0xff8a30, 0.12);

    /* ground */
    W.ground(260, 260, 0, 0, 0x040202, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x0b0604, { band: 0x140b06 });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x110905 });

    /* house: mud-brick walls, flat roof, door */
    house(W, group, 15, 0, -20, 1.0 + W.r() * 0.3, { mud: 0x0a0604 });
    house(W, group, -20, 0, -12, 0.8 + W.r() * 0.3, { mud: 0x0a0604 });

    /* hero: the altar */
    altar(W, group, 0, 0, 0, 1.4, { stone: 0x0b0604 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.40, s: 1.05 });
    person(W, group, [4.5, 0, 6], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.41, s: 1.00 });
    /* crowd: the people of the story */
    crowd(W, group, 0, 16, 23, 70, 44, [0x1a0e08, 0x0a0604, 0x040202, 0x8a6a44, 0x6a4a30, 0xc8b088]);

    return W.finish();
}

export default { build };
