/**
 * Solomon
 * ----------
 * David charges Solomon to build the house of the Lord and walks in wisdom; the old king dies and the son reigns. Stage: Jerusalem's hill with a temple site marked out, father and son on a terrace, the kingdom passing; cedar light, a quiet benediction.
 *
 * Palette 0x1a2a1a → 0x0a1408 · light: dawn · hero: house
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, cityGate, house, temple, column, oak, person, birds } from './david-kit.js';

const BG = 0x1a2a1a;
const GROUND = 0x040802;

export function build(group) {
    const W = createScene(group, { seed: 1794327536, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dawn */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-58, 30, -145], 9, 0xffd9a0);
    W.disc([-58, 30, -155], 16, 0xffb060, 0.22);
    W.stars(60, 150, [0xcfd8e8, 0xbfd0e0], 0.55);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-60, 34, -120, 24], [10, 40, -135, 30], [70, 33, -125, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xd8c8b8, { opacity: 0.5 }), [x, y, z], { s: [s, s * 0.24, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x040802, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0x030602), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [9, 0, -58], { name: 'city', r: [0, -0.07, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x0b1508, trim: 0x030602 });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x0a1308 });
    }
    W.backdrop(city);

    /* temple: colonnade and glowing doorway */
    const templeG = W.grp(group, [0, 0, -46], { name: 'temple', r: [0, -0.02, 0] });
    temple(W, templeG, 0, 0, 0, 1.1, { stone: 0x0b1609, trim: 0x121d12 });
    W.backdrop(templeG);

    /* trees: broadleaf shade */
    oak(W, group, -14.0, 0, -45.0, 1.37, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 48.5, 0, -2.8, 0.91, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 63.3, 0, -10.4, 0.99, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });

    /* hero: the house */
    house(W, group, 0, 0, -2, 1.3, { mud: 0x0a1308 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.08, s: 1.13 });
    person(W, group, [4.5, 0, 6], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.51, s: 1.19 });

    /* birds: slow circles high above */
    birds(W, group, 8, 55, { y: 26 });

    return W.finish();
}

export default { build };
