/**
 * Goliath
 * ----------
 * The Philistine giant struts between the armies; David refuses Saul's armour and steps out with staff, sling and five stones. Stage: the Valley of Elah, two armies on facing ridges, a nine-foot figure in bronze scale, a boy walking steadily toward him; dry heat, dust, a streambed glittering.
 *
 * Palette 0x2d1a0e → 0x120a04 · light: dusk · hero: staff
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, person } from './david-kit.js';

const BG = 0x2d1a0e;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 333439259, bg: BG, fogNear: 50, fogFar: 200 });

    /* light — dusk */
    W.lights({ sky: 0x7a5a8c, gnd: 0x3a2a1a, hemi: 0.6, sun: 0xff9a50, sunI: 0.85, sunPos: [45, 12, -18] });

    W.disc([55, 22, -140], 12, 0xff9a50);
    W.disc([55, 22, -150], 20, 0xff7a30, 0.18);
    W.stars(30, 150, [0xd8c8e8, 0xc8b8d8], 0.5);
    W.disc([-60, 40, -150], 30, 0x4a3a5c, 0.25);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hero: the staff */
    W.add(group, W.G('cyl', 0.09, 0.12, 5.2, 5), W.mat(0x5a3818), [0, 2.6, 0], { r: [0, 0, 0.12] });
    W.add(group, W.G('sph', 0.22, 6, 5), W.mat(0x1b1008, { metal: 0.4 }), [-0.35, 5.1, 0]);
    W.disc([0, 5, -10], 4, 0x3b2212, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, bend: 0.2, armR: [0.35, 0.1], armL: [-0.35, -0.1], ry: -0.34, s: 1.00 });

    return W.finish();
}

export default { build };
