/**
 * Absalom
 * ----------
 * Absalom's long hair catches in the branches of a great tree as his rebellion breaks in the forest of Ephraim; Joab strikes him down. Stage: a dense oak wood in rain, a royal mule at bay, tangled hair in the branches, a spear flash; cold green light, the king waiting on the road.
 *
 * Palette 0x1a1420 → 0x0a0610 · light: storm · hero: tree
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, column, throne, oak, rain, army, person } from './david-kit.js';

const BG = 0x1a1420;
const GROUND = 0x040208;

export function build(group) {
    const W = createScene(group, { seed: 1545298866, bg: BG, fogNear: 40, fogFar: 160 });

    /* light — storm */
    W.lights({ sky: 0x4a5a6c, gnd: 0x2a3238, hemi: 0.55, sun: 0xa8bcc8, sunI: 0.6, sunPos: [-30, 40, 20] });

    const clouds = W.grp(group, [0, 0, 0], { name: 'storm_clouds' });
    [[-50, 36, -110, 34], [0, 44, -130, 40], [55, 38, -115, 30], [-95, 40, -120, 28]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0x2a3238, { opacity: 0.9 }), [x, y, z], { s: [s, s * 0.3, s * 0.6] });
    });
    W.backdrop(clouds);
    W.point(0xbfd4f0, 4.0, 220, -17, 30, -40, 0.85);  // lightning flicker

    /* ground */
    W.ground(260, 260, 0, 0, 0x040208, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x0b0611, { band: 0x140f18 });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x110d15 });

    /* trees: broadleaf shade */
    oak(W, group, -64.5, 0, 9.4, 0.93, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 43.1, 0, 8.6, 1.39, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -30.0, 0, -14.0, 1.34, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -45.9, 0, -19.0, 1.40, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });

    /* storm: rain sheets across the whole frame */
    rain(W, group, 900, 230, 65, 16);

    /* army: shields and spears in rank */
    army(W, group, -9.8, 22.6, 6, { shields: [0x110d15, 0x040207, 0x8a7a2a, 0x3a5a8a] });

    /* hero: the great tree */
    oak(W, group, 0, 0, 0, 1.7, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    W.disc([0, 8, -16], 9, 0x221a2a, 0.25);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.58, s: 1.08 });

    return W.finish();
}

export default { build };
