/**
 * Covenant Friends
 * ----------------
 * Jonathan and David make a covenant, exchanging tokens — the robe, tunic, sword, bow and belt. Stage: a field outside the camp at dawn, two young men kneeling, a prince's robe passing to the shepherd; parted friends on a rising road; pale morning gold.
 *
 * Palette 0x1a1024 → 0x0a0610 · light: dusk · hero: sword
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, tent, firepit, wheat, sheep, army, person } from './david-kit.js';

const BG = 0x1a1024;
const GROUND = 0x040208;

export function build(group) {
    const W = createScene(group, { seed: 2734898778, bg: BG, fogNear: 50, fogFar: 200 });

    /* light — dusk */
    W.lights({ sky: 0x7a5a8c, gnd: 0x3a2a1a, hemi: 0.6, sun: 0xff9a50, sunI: 0.85, sunPos: [45, 12, -18] });

    W.disc([55, 22, -140], 12, 0xff9a50);
    W.disc([55, 22, -150], 20, 0xff7a30, 0.18);
    W.stars(30, 150, [0xd8c8e8, 0xc8b8d8], 0.5);
    W.disc([-60, 40, -150], 30, 0x4a3a5c, 0.25);

    /* ground */
    W.ground(260, 260, 0, 0, 0x040208, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* camp: a circle of tents, smoke rising */
    tent(W, group, -1.0, 0, -18.1, 1.02, 0xc8b088, W.r() * 6);
    tent(W, group, -29.1, 0, -5.9, 1.20, 0xd8c8a0, W.r() * 6);
    tent(W, group, -18.3, 0, -13.9, 1.32, 0x8a6a44, W.r() * 6);
    tent(W, group, -26.2, 0, -18.1, 1.38, 0xd8c8a0, W.r() * 6);
    firepit(W, group, 8.2, 0, -2.8, 1.0);

    /* fields: standing grain to the horizon */
    wheat(W, group, 0, 34, 220, 110, { h: 2.1, stalk: 0x1d1228, head: 0x21142d });

    /* flock: sheep grazing */
    sheep(W, group, -12.6, 0, 3.3, W.r() * 6, 0.90);
    sheep(W, group, 16.2, 0, 8.5, W.r() * 6, 0.84);
    sheep(W, group, 13.7, 0, 11.7, W.r() * 6, 0.98);
    sheep(W, group, 2.0, 0, 8.4, W.r() * 6, 0.84);
    /* army: shields and spears in rank */
    army(W, group, 11.2, 23.8, 8, { shields: [0x110a17, 0x040207, 0x8a7a2a, 0x3a5a8a] });

    /* hero: the sword */
    const sw = W.grp(group, [0, 0.1, 0], { r: [0, 0.6, 0.35], name: 'sword' });
    W.add(sw, W.G('box', 0.16, 3.4, 0.4), W.mat(0xb8c0c8, { metal: 0.7, rough: 0.25 }), [0, 2.1, 0]);
    W.add(sw, W.G('box', 0.9, 0.14, 0.5), W.mat(0x100a16, { metal: 0.5 }), [0, 0.5, 0]);
    W.add(sw, W.G('cyl', 0.09, 0.12, 0.8, 5), W.mat(0x4a2c14), [0, 0.1, 0]);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, bend: 0.55, armR: [-0.4, 0.2], armL: [-0.3, -0.2], ry: 0.25, s: 1.19 });
    person(W, group, [4.5, 0, 6], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, bend: 0.55, armR: [-0.4, 0.2], armL: [-0.3, -0.2], ry: 0.42, s: 1.02 });

    return W.finish();
}

export default { build };
