/**
 * Nathan's Parable
 * ----------------
 * The prophet Nathan tells the rich man with many sheep who takes the poor man's one ewe lamb — and David condemns himself. Stage: a candlelit chamber, the prophet with a staff, the king listening; two flocks in the background, one rich, one poor; a single lamp and a long silence.
 *
 * Palette 0x241a10 → 0x100a04 · light: dusk · hero: staff
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, column, throne, house, sheep, person } from './david-kit.js';

const BG = 0x241a10;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 861368219, bg: BG, fogNear: 50, fogFar: 200 });

    /* light — dusk */
    W.lights({ sky: 0x7a5a8c, gnd: 0x3a2a1a, hemi: 0.6, sun: 0xff9a50, sunI: 0.85, sunPos: [45, 12, -18] });

    W.disc([55, 22, -140], 12, 0xff9a50);
    W.disc([55, 22, -150], 20, 0xff7a30, 0.18);
    W.stars(30, 150, [0xd8c8e8, 0xc8b8d8], 0.5);
    W.disc([-60, 40, -150], 30, 0x4a3a5c, 0.25);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x110b04, { band: 0x1b140c });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x17110a });

    /* house: mud-brick walls, flat roof, door */
    house(W, group, -12, 0, -19, 1.0 + W.r() * 0.3, { mud: 0x0f0a04 });
    house(W, group, 22, 0, -13, 0.8 + W.r() * 0.3, { mud: 0x100a04 });

    /* flock: sheep grazing */
    sheep(W, group, 6.2, 0, 10.5, W.r() * 6, 0.84);
    sheep(W, group, 14.4, 0, -4.7, W.r() * 6, 1.15);
    sheep(W, group, 15.4, 0, -9.0, W.r() * 6, 1.14);
    sheep(W, group, -8.5, 0, -7.5, W.r() * 6, 0.97);
    sheep(W, group, -18.0, 0, 5.2, W.r() * 6, 1.14);
    sheep(W, group, 7.2, 0, -2.3, W.r() * 6, 0.80);
    sheep(W, group, 12.5, 0, -5.4, W.r() * 6, 1.15);

    /* hero: the staff */
    W.add(group, W.G('cyl', 0.09, 0.12, 5.2, 5), W.mat(0x5a3818), [0, 2.6, 0], { r: [0, 0, 0.12] });
    W.add(group, W.G('sph', 0.22, 6, 5), W.mat(0x16100a, { metal: 0.4 }), [-0.35, 5.1, 0]);
    W.disc([0, 5, -10], 4, 0x2f2215, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.46, s: 1.15 });

    return W.finish();
}

export default { build };
