/**
 * Abigail
 * ----------
 * Abigail rides out with provisions to meet David before Nabal's foolishness becomes bloodshed, and she speaks peace. Stage: a donkey train descending a dry ravine at noon, a wise woman carrying loaves and wine, David's band armed on the ridge; terracotta, dust, and a tense standoff turning to grace.
 *
 * Palette 0x1a2a14 → 0x0a1408 · light: dusk · hero: pillar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, vineyard, pillar, person, birds } from './david-kit.js';

const BG = 0x1a2a14;
const GROUND = 0x040802;

export function build(group) {
    const W = createScene(group, { seed: 2263420828, bg: BG, fogNear: 50, fogFar: 200 });

    /* light — dusk */
    W.lights({ sky: 0x7a5a8c, gnd: 0x3a2a1a, hemi: 0.6, sun: 0xff9a50, sunI: 0.85, sunPos: [45, 12, -18] });

    W.disc([55, 22, -140], 12, 0xff9a50);
    W.disc([55, 22, -150], 20, 0xff7a30, 0.18);
    W.stars(30, 150, [0xd8c8e8, 0xc8b8d8], 0.5);
    W.disc([-60, 40, -150], 30, 0x4a3a5c, 0.25);

    /* ground */
    W.ground(260, 260, 0, 0, 0x040802, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0x030602), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* vineyard: posts, canopies, hanging fruit */
    vineyard(W, group, 0, 30, 40, 80, { leaf: 0x4f8a2e, berry: 0x121d0e });

    /* hero: the standing stone */
    pillar(W, group, 0, 0, 0, 1.15, { stone: 0x0a1408 });
    W.disc([0, 6, -12], 5, 0x22371a, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.48, s: 1.20 });
    person(W, group, [4.5, 0, 6], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.46, s: 1.12 });
    person(W, group, [1, 0, -5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.51, s: 1.18 });

    /* birds: slow circles high above */
    birds(W, group, 8, 55, { y: 26 });

    return W.finish();
}

export default { build };
