/**
 * Saul's Court
 * ------------
 * David plays the lyre for Saul, and the king's torment eases while his jealousy stirs. Stage: a dim throne room at night, a boy with a harp, the king looming on a chair, a spear at his belt; firelight flickering on stone; tension beneath the melody.
 *
 * Palette 0x2a1a10 → 0x120a04 · light: ember · hero: throne
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, column, throne, house, army, person } from './david-kit.js';

const BG = 0x2a1a10;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 1624336040, bg: BG, fogNear: 45, fogFar: 180 });

    /* light — ember */
    W.lights({ sky: 0x3a2418, gnd: 0x1a0e08, hemi: 0.4, sun: 0xff7a30, sunI: 0.7, sunPos: [20, 26, 30] });

    W.stars(90, 150, [0xf0e0c8, 0xd8c0a0], 0.7);
    W.disc([0, 34, -150], 14, 0xff8a30, 0.12);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x130b04, { band: 0x20140c });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x1b110a });

    /* house: mud-brick walls, flat roof, door */
    house(W, group, 16, 0, -20, 1.0 + W.r() * 0.3, { mud: 0x110a04 });
    house(W, group, -24, 0, -17, 0.8 + W.r() * 0.3, { mud: 0x120a04 });

    /* army: shields and spears in rank */
    army(W, group, 5.7, 20.2, 10, { shields: [0x1b110a, 0x050402, 0x8a7a2a, 0x3a5a8a] });

    /* hero: the throne */
    throne(W, group, 0, 0, 0, 1.5, { gold: 0x1b110a });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.07, s: 1.14 });
    person(W, group, [4.5, 0, 6], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.53, s: 1.15 });

    return W.finish();
}

export default { build };
