/**
 * The Throne
 * ----------
 * David is anointed king over all Israel at Hebron and takes Jerusalem, the city of Jebus, for his capital. Stage: a water shaft climbing to the city gate, warriors ascending, the king on a throne of stone on the citadel; olive hills, bronze light, banners.
 *
 * Palette 0x2a1a10 → 0x120a04 · light: ember · hero: throne
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./david-kit.js.
 */

import { THREE, createScene, water, cityGate, house, column, throne, oak, person } from './david-kit.js';

const BG = 0x2a1a10;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 1716148531, bg: BG, fogNear: 45, fogFar: 180 });

    /* light — ember */
    W.lights({ sky: 0x3a2418, gnd: 0x1a0e08, hemi: 0.4, sun: 0xff7a30, sunI: 0.7, sunPos: [20, 26, 30] });

    W.stars(90, 150, [0xf0e0c8, 0xd8c0a0], 0.7);
    W.disc([0, 34, -150], 14, 0xff8a30, 0.12);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x020101, 0x150c05);
    W.ground(260, 95, 0, 60, 0x060402, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x050302, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x030201), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x030201), [0, -0.05, -14.6]);

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [-19, 0, -58], { name: 'city', r: [0, -0.10, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x130b04, trim: 0x050302 });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x110a04 });
    }
    W.backdrop(city);

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x130b04, { band: 0x20140c });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x1b110a });

    /* trees: broadleaf shade */
    oak(W, group, -59.3, 0, -18.0, 1.03, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 58.9, 0, -3.4, 1.13, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -28.1, 0, -43.9, 0.97, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -1.8, 0, -0.4, 1.27, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });

    /* hero: the throne */
    throne(W, group, 0, 0, 11, 1.5, { gold: 0x1b110a });

    /* figures */
    person(W, group, [-5, 0, 16], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.54, s: 1.12 });

    return W.finish();
}

export default { build };
