/**
 * Bethel
 * ----------
 * Jacob flees and sleeps with a stone for a pillow, dreaming of a ladder to heaven with angels ascending and descending. Stage: a night under the open sky, a lone figure on the ground, a great stair of light touching the sky; stars, and the Lord standing above it.
 *
 * Palette 0x2a1a10 → 0x060402 · light: ember · hero: pillar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./jacob-kit.js.
 */

import { THREE, createScene, cityGate, house, pillar, person } from './jacob-kit.js';

const BG = 0x2a1a10;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 1368300474, bg: BG, fogNear: 45, fogFar: 180 });

    /* light — ember */
    W.lights({ sky: 0x3a2418, gnd: 0x1a0e08, hemi: 0.4, sun: 0xff7a30, sunI: 0.7, sunPos: [20, 26, 30] });

    W.stars(90, 150, [0xf0e0c8, 0xd8c0a0], 0.7);
    W.disc([0, 34, -150], 14, 0xff8a30, 0.12);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [-10, 0, -58], { name: 'city', r: [0, 0.08, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x060402, trim: 0x050302 });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x060402 });
    }
    W.backdrop(city);

    /* hero: the standing stone */
    pillar(W, group, 0, 0, 0, 1.15, { stone: 0x060402 });
    W.disc([0, 6, -12], 5, 0x372215, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x2a1a10, bend: 0.02, ry: 0.67, s: 1.08 });
    person(W, group, [4.5, 0, 6], { robe: 0x060402, bend: 0.02, ry: -0.06, s: 1.15 });

    return W.finish();
}

export default { build };
