/**
 * Naaman
 * ----------
 * Naaman, commander of Aram, comes with horses and chariots to be healed of leprosy; Elisha sends him to wash seven times in the Jordan. Stage: a riverbank with a retinue of chariots and horsemen, the proud commander wading to his waist, seven immersions; water gleaming, pride yielding.
 *
 * Palette 0x1a2a14 → 0x060402 · light: ember · hero: water
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./elisha-kit.js.
 */

import { THREE, createScene, water, rock, person } from './elisha-kit.js';

const BG = 0x1a2a14;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 851429175, bg: BG, fogNear: 45, fogFar: 180 });

    /* light — ember */
    W.lights({ sky: 0x3a2418, gnd: 0x1a0e08, hemi: 0.4, sun: 0xff7a30, sunI: 0.7, sunPos: [20, 26, 30] });

    W.stars(90, 150, [0xf0e0c8, 0xd8c0a0], 0.7);
    W.disc([0, 34, -150], 14, 0xff8a30, 0.12);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x020101, 0x070502);
    W.ground(260, 95, 0, 60, 0x060402, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x050302, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x030201), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x030201), [0, -0.05, -14.6]);

    /* hero: the water — a focal stone in the flow */
    rock(W, group, 0, 0, 11, 1.7, 0x050402);

    /* figures */
    person(W, group, [-5, 0, 16], { robe: 0x8a6a44, head: 'wrap', wrap: 0x1e3017, wrapTrim: 0x121d0e, beard: 'long', staff: 'planted', ry: 0.22, s: 1.01 });

    return W.finish();
}

export default { build };
