const chapters=[
 {eyebrow:'Chapter One · Judges 4:1–5',title:'A Voice Beneath the Palm',text:'Israel had forgotten the ways of peace, and fear lay over the land. Yet beneath a palm tree in the hills of Ephraim sat Deborah—a prophet, a judge, and a listener. People came to her with tangled troubles, and she answered with wisdom and courage.',verse:'“The Israelites went up to her to have their disputes decided.” — Judges 4:5',bg:'hills',mid:'palm',fg:'wildflowers',left:'deborah',game:'wisdom',gameTitle:'Choose the wise path',instructions:'Help Deborah answer with fairness. Choose the response that brings truth and peace.'},
 {eyebrow:'Chapter Two · Judges 4:6–10',title:'The Call to Courage',text:'God gave Deborah a message for Barak: gather the people and lead them to Mount Tabor. Barak was afraid, but Deborah did not shame him. “I will go with you,” she said. Courage began with a promise that no one had to stand alone.',verse:'“Certainly I will go with you.” — Judges 4:9',bg:'tabor',mid:'camp',fg:'grasses',left:'deborah',right:'barak',game:'sequence',gameTitle:'Gather the people',instructions:'Put the preparations in the wisest order. Tap: listen, gather, then go.'},
 {eyebrow:'Chapter Three · Judges 4:12–23',title:'The River Rose',text:'Sisera came with iron chariots, certain that strength would win the day. Deborah gave the signal. Barak and his people swept down Mount Tabor—and the heavens opened. The Kishon River flooded; the heavy chariots sank into mud, and the frightened army scattered.',verse:'“Up! This is the day the Lord has given Sisera into your hands.” — Judges 4:14',bg:'storm',mid:'chariots',fg:'river',left:'barak',game:'river',gameTitle:'Turn the tide',instructions:'Tap every iron chariot before it crosses the rushing Kishon.'},
 {eyebrow:'Chapter Four · Judges 5',title:'A Song of Peace',text:'When the danger had passed, Deborah and Barak sang. They remembered every willing heart, every brave step, and the God who had gone before them. The land rested for forty years. Deborah’s story reminds us: listen closely, stand together, and use courage to make peace.',verse:'“When the princes in Israel take the lead, when the people willingly offer themselves—praise the Lord!” — Judges 5:2',bg:'dawn',mid:'village',fg:'laurels',left:'deborah',right:'barak',game:'song',gameTitle:'Build the victory song',instructions:'Choose the three words that best tell Deborah’s story.'}
];
const el=id=>document.getElementById(id);let chapter=0,gameOpen=false,completed=new Set(),soundOn=true,sequence=[];
function render(){const c=chapters[chapter];['eyebrow','title','text','verse'].forEach(k=>el(k).textContent=c[k]);el('stamp').textContent=`Chapter ${chapter+1} of ${chapters.length}`;el('background').src=`assets/backgrounds/${c.bg}.svg`;el('midground').src=`assets/midgrounds/${c.mid}.svg`;el('foreground').src=`assets/foregrounds/${c.fg}.svg`;setChar('characterLeft',c.left);setChar('characterRight',c.right);el('gameTitle').textContent=c.gameTitle;el('gameInstructions').textContent=c.instructions;el('gamePanel').classList.toggle('open',gameOpen);el('gameMessage').textContent='';document.querySelector('[data-action="previous"]').disabled=chapter===0;document.querySelector('[data-action="next"]').textContent=gameOpen?(completed.has(chapter)?(chapter===3?'Read again':'Next chapter'):'Finish challenge'):'Begin challenge';renderDots();if(gameOpen)renderGame(c.game)}
function setChar(id,name){const node=el(id);node.hidden=!name;if(name){node.src=`assets/characters/${name}.svg`;node.alt=name[0].toUpperCase()+name.slice(1)}}
function renderDots(){document.querySelector('.chapter-dots').innerHTML=chapters.map((_,i)=>`<button class="chapter-dot ${i===chapter?'active':''} ${completed.has(i)?'complete':''}" data-chapter="${i}" aria-label="Go to chapter ${i+1}"></button>`).join('')}
function renderGame(type){sequence=[];const area=el('gameArea');if(type==='wisdom')area.innerHTML=`<div class="choice-grid"><button class="choice" data-answer="wrong">Choose the loudest person</button><button class="choice" data-answer="right">Listen to both sides and seek truth</button><button class="choice" data-answer="wrong">Decide before hearing the story</button></div>`;if(type==='sequence')area.innerHTML=`<div class="sequence-grid">${[['gather','2 · Gather the people'],['go','3 · Go to Mount Tabor'],['listen','1 · Listen to God']].map(x=>`<button class="sequence-card" data-step="${x[0]}">${x[1]}</button>`).join('')}</div>`;if(type==='river')area.innerHTML=`<div class="river-game">${[1,2,3,4].map(n=>`<button class="river-token" data-chariot="${n}">Iron chariot</button>`).join('')}</div>`;if(type==='song')area.innerHTML=`<div class="song-words">${['Courage','Wisdom','Together','Pride','Fear','Power'].map(w=>`<button class="song-word" data-word="${w}">${w}</button>`).join('')}</div>`}
function win(msg){completed.add(chapter);el('gameMessage').textContent=msg;renderDots();document.querySelector('[data-action="next"]').textContent=chapter===3?'Read again':'Next chapter';tone(660)}
function tone(freq=440){if(!soundOn)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.06,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.18)}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='home'){chapter=0;gameOpen=false;render()}if(action==='sound'){soundOn=!soundOn;e.target.textContent=soundOn?'♪':'×'}if(action==='previous'){chapter--;gameOpen=false;render()}if(action==='next'){if(!gameOpen){gameOpen=true;render();setTimeout(()=>el('gamePanel').scrollIntoView({behavior:'smooth',block:'center'}),50)}else if(completed.has(chapter)){chapter=chapter===3?0:chapter+1;gameOpen=false;render();scrollTo({top:0,behavior:'smooth'})}else el('gameMessage').textContent='Complete the challenge to continue.'}const dot=e.target.closest('[data-chapter]');if(dot){chapter=+dot.dataset.chapter;gameOpen=false;render()}
 const choice=e.target.closest('[data-answer]');if(choice){if(choice.dataset.answer==='right'){choice.classList.add('correct');win('Wise choice! Listening makes room for justice.')}else{choice.classList.add('wrong');el('gameMessage').textContent='Try again—wisdom begins by listening.'}}
 const step=e.target.closest('[data-step]');if(step&&!step.classList.contains('selected')){step.classList.add('selected');sequence.push(step.dataset.step);tone(400+sequence.length*80);if(sequence.length===3){if(sequence.join()==='listen,gather,go')win('Ready! Courage grows one faithful step at a time.');else{el('gameMessage').textContent='Almost. Begin by listening, then gather, then go.';setTimeout(()=>{document.querySelectorAll('.sequence-card').forEach(x=>x.classList.remove('selected'));sequence=[]},700)}}}
 const ch=e.target.closest('[data-chariot]');if(ch){ch.style.transform='translateY(130px) rotate(12deg)';ch.style.opacity='.25';ch.disabled=true;tone(240);if([...document.querySelectorAll('[data-chariot]')].every(x=>x.disabled))win('The chariots are stuck—the tide has turned!')}
 const word=e.target.closest('[data-word]');if(word){word.classList.toggle('chosen');const picked=[...document.querySelectorAll('.song-word.chosen')].map(x=>x.dataset.word);if(picked.length===3){if(['Courage','Wisdom','Together'].every(x=>picked.includes(x)))win('A song worth remembering: courage, wisdom, together!');else el('gameMessage').textContent='Those words make a song—but which three tell Deborah’s story best?'}}});
render();