/**
 * Moriah
 * ----------
 * God tests Abraham: take Isaac to Moriah and offer him as a burnt offering; at the last moment a ram is caught in the thicket. Stage: a bare stone mountain at dawn, wood stacked on Isaac's back, the altar of unhewn stone, the angel's hand staying the knife; a ram in a nearby thorn bush, cold gold light.
 *
 * Palette 0xd8b878 → 0x9c8456 · light: dawn · hero: altar
 * Game beat: Climb, gather wood, and respond to the provided ram.
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./abraham-kit.js.
 */

import { THREE, createScene, oak, flame, sheep, altar, person, birds } from './abraham-kit.js';

const BG = 0xd8b878;
const GROUND = 0x776542;

export function build(group) {
    const W = createScene(group, { seed: 1486370199, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dawn */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-58, 30, -145], 9, 0xffd9a0);
    W.disc([-58, 30, -155], 16, 0xffb060, 0.22);
    W.stars(60, 150, [0xcfd8e8, 0xbfd0e0], 0.55);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-60, 34, -120, 24], [10, 40, -135, 30], [70, 33, -125, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xd8c8b8, { opacity: 0.5 }), [x, y, z], { s: [s, s * 0.24, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x776542, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0x594c32), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* trees: broadleaf shade */
    oak(W, group, -28.2, 0, -36.9, 1.37, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -3.7, 0, -3.4, 1.11, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -8.7, 0, -47.1, 1.19, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 45.3, 0, 2.6, 1.00, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });

    /* fire: the burning mark */
    flame(W, group, 5.6, 0, -4.1, 1.1);
    W.point(0xff8a30, 2.0, 55, 0, 3, 0, 0.35);

    /* flock: sheep grazing */
    sheep(W, group, 4.9, 0, -0.9, W.r() * 6, 0.81);
    sheep(W, group, 14.3, 0, 12.0, W.r() * 6, 1.14);
    sheep(W, group, 16.1, 0, 7.7, W.r() * 6, 0.99);
    sheep(W, group, 0.8, 0, 4.2, W.r() * 6, 1.02);
    sheep(W, group, 10.0, 0, -4.1, W.r() * 6, 0.94);

    /* hero: the altar */
    altar(W, group, 0, 0, 0, 1.4, { stone: 0xa48b5a });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xd8b878, ry: 0.16, s: 1.08 });
    person(W, group, [4.5, 0, 6], { robe: 0x9c8456, ry: -0.17, s: 1.18 });

    /* birds: slow circles high above */
    birds(W, group, 5, 55, { y: 26 });

    return W.finish();
}

export default { build };
