/**
 * Mount Carmel
 * ------------
 * Elijah repairs the altar with twelve stones, drenches it with water, and calls down fire while the prophets of Baal cry out in vain. Stage: a ruined altar on a bare mountain headland, twelve stones, water running, a pillar of fire at dusk; the sea below, a crowd of prophets in panic.
 *
 * Palette 0x5a3e2b → 0x3b2a1a · light: dust · hero: altar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./eiljah-kit.js.
 */

import { THREE, createScene, water, flame, altar, person, crowd, birds } from './eiljah-kit.js';

const BG = 0x5a3e2b;
const GROUND = 0x3b2a1a;

export function build(group) {
    const W = createScene(group, { seed: 3997896392, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dust */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x150f09, 0x44301e);
    W.ground(260, 95, 0, 60, 0x3b2a1a, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x322416, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x20170e), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x20170e), [0, -0.05, -14.6]);

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0x2c2014), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* fire: the burning mark */
    flame(W, group, 1.4, 0, -6.4, 1.1);
    W.point(0xff8a30, 2.0, 55, 0, 3, 0, 0.35);

    /* hero: the altar */
    altar(W, group, 0, 0, 11, 1.4, { stone: 0x3e2c1b });

    /* figures */
    person(W, group, [-5, 0, 16], { robe: 0x8a6a44, head: 'wrap', wrap: 0x674731, wrapTrim: 0x3f2b1e, beard: 'long', staff: 'planted', bend: 0.2, armR: [0.35, 0.1], armL: [-0.35, -0.1], ry: 0.64, s: 1.18 });
    /* crowd: the people of the story */
    crowd(W, group, 0, 16, 16, 70, 44, [0x5a3e2b, 0x3b2a1a, 0x8a6a44, 0x6a4a30, 0xc8b088, 0x5a4a6a]);

    /* birds: slow circles high above */
    birds(W, group, 5, 55, { y: 26 });

    return W.finish();
}

export default { build };
