/**
 * The Child Restored
 * ------------------
 * The widow's son falls ill and dies; Elijah carries him upstairs, stretches himself on the boy three times, and prays until life returns. Stage: a rooftop chamber at night, the prophet on the bed, the boy still, then stirring; a single oil lamp, deep shadow, held breath.
 *
 * Palette 0x8b2500 → 0x3d1200 · light: wind_carmel · hero: pillar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./eiljah-kit.js.
 */

import { THREE, createScene, house, jar, pillar, person, birds } from './eiljah-kit.js';

const BG = 0x8b2500;
const GROUND = 0x1a0700;

export function build(group) {
    const W = createScene(group, { seed: 2841985810, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — wind_carmel */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x1a0700, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0x140500), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* house: mud-brick walls, flat roof, door */
    house(W, group, -15, 0, -14, 1.0 + W.r() * 0.3, { mud: 0x3a1100 });

    jar(W, group, -1.6, 0, -4.4, );

    /* hero: the standing stone */
    pillar(W, group, 0, 0, 0, 1.15, { stone: 0x3d1200 });
    W.disc([0, 6, -12], 5, 0xb53000, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x8a6a44, head: 'wrap', wrap: 0xa02b00, wrapTrim: 0x611a00, beard: 'long', staff: 'planted', ry: -0.66, s: 1.11 });
    person(W, group, [4.5, 0, 6], { robe: 0x8a6a44, head: 'wrap', wrap: 0xa02b00, wrapTrim: 0x611a00, beard: 'long', staff: 'planted', ry: 0.60, s: 1.16 });
    person(W, group, [1, 0, -5], { robe: 0x8a6a44, head: 'wrap', wrap: 0xa02b00, wrapTrim: 0x611a00, beard: 'long', staff: 'planted', ry: 0.01, s: 1.20 });

    /* birds: slow circles high above */
    birds(W, group, 7, 55, { y: 26 });

    return W.finish();
}

export default { build };
