/**
 * The Drought
 * -----------
 * Elijah the Tishbite proclaims a drought and is sent to the brook Cherith, where ravens bring him bread and meat. Stage: a cracked brook bed in a limestone wadi, a lone prophet in patched cloth, ravens landing with crusts; dust, heat shimmer, a dry riverbed.
 *
 * Palette 0xf2a65a → 0x774f38 · light: dust · hero: bread
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./eiljah-kit.js.
 */

import { THREE, createScene, water, wheat, person } from './eiljah-kit.js';

const BG = 0xf2a65a;
const GROUND = 0x774f38;

export function build(group) {
    const W = createScene(group, { seed: 2201148937, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dust */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x2a1c14, 0x895b40);
    W.ground(260, 95, 0, 60, 0x774f38, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x654330, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x412b1f), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x412b1f), [0, -0.05, -14.6]);

    /* fields: standing grain to the horizon */
    wheat(W, group, 0, 34, 220, 110, { h: 2.1, stalk: 0xffb763, head: 0xffd071 });

    /* hero: the bread */
    for (let i = 0; i < 3; i++) {
        W.add(group, W.G('dod', 0.5), W.mat(0xd8b878, { rough: 0.7 }), [0 - 1 + i, 0.35, 11 + (i % 2) * 0.8 - 0.4], { s: [1, 0.5, 0.8] });
    }
    W.disc([0, 3.5, 1], 3, 0xffd875, 0.3);

    /* figures */
    person(W, group, [-5, 0, 16], { robe: 0x8a6a44, head: 'wrap', wrap: 0xffbf67, wrapTrim: 0xa9743f, beard: 'long', ry: -0.35, s: 1.01 });
    person(W, group, [4.5, 0, 17], { robe: 0x8a6a44, head: 'wrap', wrap: 0xffbf67, wrapTrim: 0xa9743f, beard: 'long', ry: -0.59, s: 1.18 });

    return W.finish();
}

export default { build };
