/**
 * The Rain Returns
 * ----------------
 * Elijah prays seven times, a cloud no bigger than a man's hand rises over the sea, and he runs before Ahab's chariot to Jezreel. Stage: a headland at sunset, a small cloud, the sky darkening, the prophet running with his cloak flying; rain sweeping in, black clouds and gold rifts.
 *
 * Palette 0x0d1b2a → 0x061224 · light: constellation · hero: chariot
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./eiljah-kit.js.
 */

import { THREE, createScene, water, rain, chariot, person } from './eiljah-kit.js';

const BG = 0x0d1b2a;
const GROUND = 0x030b18;

export function build(group) {
    const W = createScene(group, { seed: 1069334412, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — constellation */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x010408, 0x071529);
    W.ground(260, 95, 0, 60, 0x030b18, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x030914, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x02060d), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x02060d), [0, -0.05, -14.6]);

    /* storm: rain sheets across the whole frame */
    rain(W, group, 900, 230, 65, 16);

    /* chariot: gold-trimmed cab and spoked wheels */
    chariot(W, group, -7.2, 0, -5.3, 1.1, { ry: 0.52, gold: 0x081019 });

    /* hero: the chariot */
    chariot(W, group, 0, 0, 11, 1.25, { ry: 0.3, gold: 0x081019 });

    /* figures */
    person(W, group, [-5, 0, 16], { robe: 0x8a6a44, head: 'wrap', wrap: 0x0f1f30, wrapTrim: 0x09131d, beard: 'long', staff: 'planted', bend: 0.2, armR: [0.35, 0.1], armL: [-0.35, -0.1], ry: 0.48, s: 1.06 });
    person(W, group, [4.5, 0, 17], { robe: 0x8a6a44, head: 'wrap', wrap: 0x0f1f30, wrapTrim: 0x09131d, beard: 'long', staff: 'planted', bend: 0.2, armR: [0.35, 0.1], armL: [-0.35, -0.1], ry: -0.36, s: 1.05 });
    person(W, group, [1, 0, 6], { robe: 0x8a6a44, head: 'wrap', wrap: 0x0f1f30, wrapTrim: 0x09131d, beard: 'long', staff: 'planted', bend: 0.2, armR: [0.35, 0.1], armL: [-0.35, -0.1], ry: -0.39, s: 1.12 });

    return W.finish();
}

export default { build };
