/**
 * The Widow's Jar
 * ---------------
 * At Zarephath a widow shares her last flour and oil, and Elijah keeps her jar and bowl from emptying through the drought. Stage: a tiny Phoenician kitchen, a handful of flour, a cruse of oil, a boy gathering sticks; a miracle of measure in a windowless room, one lamp.
 *
 * Palette 0xc6a776 → 0x8c6c4f · light: dream · hero: jar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./eiljah-kit.js.
 */

import { THREE, createScene, house, cup, jar, person, crowd } from './eiljah-kit.js';

const BG = 0xc6a776;
const GROUND = 0x594236;

export function build(group) {
    const W = createScene(group, { seed: 1626632120, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dream */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x594236, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* house: mud-brick walls, flat roof, door */
    house(W, group, -15, 0, -20, 1.0 + W.r() * 0.3, { mud: 0x85674b });
    house(W, group, -18, 0, -17, 0.8 + W.r() * 0.3, { mud: 0x8c6c4f });

    cup(W, group, -6.2, 0, -7.1, );

    /* hero: the jar */
    jar(W, group, 0, 0, 0, 1.25, { clay: 0x7e6147 });
    W.disc([0, 4, -10], 4, 0xffd999, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x8a6a44, head: 'wrap', wrap: 0xe4c088, wrapTrim: 0x8b7553, beard: 'long', ry: -0.01, s: 1.12 });
    person(W, group, [4.5, 0, 6], { robe: 0x8a6a44, head: 'wrap', wrap: 0xe4c088, wrapTrim: 0x8b7553, beard: 'long', ry: 0.07, s: 1.04 });
    person(W, group, [1, 0, -5], { robe: 0x8a6a44, head: 'wrap', wrap: 0xe4c088, wrapTrim: 0x8b7553, beard: 'long', ry: -0.52, s: 1.06 });
    /* crowd: the people of the story */
    crowd(W, group, 0, 16, 15, 70, 44, [0xc6a776, 0x8c6c4f, 0x594236, 0x8a6a44, 0x6a4a30, 0xc8b088]);

    return W.finish();
}

export default { build };
