/**
 * The Quiet Voice
 * ---------------
 * At Horeb the Lord passes in wind, earthquake and fire — and speaks in a sound of sheer silence; Elijah wraps his face in his mantle. Stage: a cave mouth on the mountain, the prophet listening in the dark, the wind outside bending the scrub; an enormous stillness in the frame.
 *
 * Palette 0xffde7d → 0xff914d · light: wind_chariot · hero: chariot
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./eiljah-kit.js.
 */

import { THREE, createScene, flame, chariot, person, birds } from './eiljah-kit.js';

const BG = 0xffde7d;
const GROUND = 0xff914d;

export function build(group) {
    const W = createScene(group, { seed: 3186884030, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — wind_chariot */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0xff914d, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0xbf6d3a), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* fire: the burning mark */
    flame(W, group, 5.6, 0, -4.9, 1.1);
    W.point(0xff8a30, 2.0, 55, 0, 3, 0, 0.35);

    /* chariot: gold-trimmed cab and spoked wheels */
    chariot(W, group, 1.0, 0, -5.0, 1.1, { ry: 0.45, gold: 0x99854b });

    /* hero: the chariot */
    chariot(W, group, 0, 0, 0, 1.25, { ry: 0.3, gold: 0x99854b });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x8a6a44, head: 'wrap', wrap: 0xffff90, wrapTrim: 0xb39b58, beard: 'long', staff: 'planted', ry: -0.18, s: 1.08 });
    person(W, group, [4.5, 0, 6], { robe: 0x8a6a44, head: 'wrap', wrap: 0xffff90, wrapTrim: 0xb39b58, beard: 'long', staff: 'planted', ry: -0.16, s: 1.01 });
    person(W, group, [1, 0, -5], { robe: 0x8a6a44, head: 'wrap', wrap: 0xffff90, wrapTrim: 0xb39b58, beard: 'long', staff: 'planted', ry: 0.02, s: 1.08 });

    /* birds: slow circles high above */
    birds(W, group, 5, 55, { y: 26 });

    return W.finish();
}

export default { build };
