/**
 * Obed
 * ----------
 * The women say: a son has been born to Naomi, and they name him Obed, the father of Jesse, the father of David. Stage: a house at dawn, a newborn child, a grandmother holding him, the women of the neighbourhood at the door; a line beginning.
 *
 * Palette 0xd8b878 → 0x9c8456 · light: dawn · hero: house
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./ruth-kit.js.
 */

import { THREE, createScene, house, person } from './ruth-kit.js';

const BG = 0xd8b878;
const GROUND = 0x776542;

export function build(group) {
    const W = createScene(group, { seed: 4164501758, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dawn */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-58, 30, -145], 9, 0xffd9a0);
    W.disc([-58, 30, -155], 16, 0xffb060, 0.22);
    W.stars(60, 150, [0xcfd8e8, 0xbfd0e0], 0.55);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-60, 34, -120, 24], [10, 40, -135, 30], [70, 33, -125, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xd8c8b8, { opacity: 0.5 }), [x, y, z], { s: [s, s * 0.24, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x776542, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* house: mud-brick walls, flat roof, door */
    house(W, group, 18, 0, -17, 1.0 + W.r() * 0.3, { mud: 0x947d52 });
    house(W, group, 23, 0, -13, 0.8 + W.r() * 0.3, { mud: 0x9c8456 });

    /* hero: the house */
    house(W, group, 0, 0, -2, 1.3, { mud: 0x947d52 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.12, s: 1.01 });
    person(W, group, [4.5, 0, 6], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.55, s: 1.04 });

    return W.finish();
}

export default { build };
