/**
 * The Long Wait
 * -------------
 * Noah sends out a raven, then a dove; the dove returns with an olive leaf, and the waters are drying. Stage: the ark on a quiet sea at dawn, a dove returning to the window, a branch of olive in its beak; the first sign of the world coming back.
 *
 * Palette 0x0c1428 → 0x060a18 · light: flood · hero: ark
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./noah-kit.js.
 */

import { THREE, createScene, water, oak, ark, person, birds } from './noah-kit.js';

const BG = 0x0c1428;
const GROUND = 0x020408;

export function build(group) {
    const W = createScene(group, { seed: 2429329158, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — flood */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x010103, 0x070c1c);
    W.ground(260, 95, 0, 60, 0x020408, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x020307, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x010204), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x010204), [0, -0.05, -14.6]);

    /* trees: broadleaf shade */
    oak(W, group, -47.7, 0, -22.6, 0.96, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 23.4, 0, 4.1, 1.12, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 11.9, 0, -31.9, 1.36, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 6.8, 0, -55.3, 1.33, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });

    /* hero: the ark riding the flood */
    ark(W, group, 0, 0.2, 0, 1.0, { ry: 0.25 });

    /* hero: the ark */
    ark(W, group, 0, 0.2, 0, 1.1, { ry: 0.2 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x0c1428, ry: 0.20, s: 1.17 });

    /* birds: slow circles high above */
    birds(W, group, 6, 55, { y: 26 });

    return W.finish();
}

export default { build };
