/**
 * The Warning
 * -----------
 * The Lord warns Noah of the coming flood, and he is told to make an ark of gopher wood, for the earth is filled with violence. Stage: a plain at dusk, a man listening to a voice, the world behind him darkening, the first rain cloud on the horizon; a lone figure in a field.
 *
 * Palette 0x2e2010 → 0x14100a · light: dusk · hero: ark
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./noah-kit.js.
 */

import { THREE, createScene, water, temple, column, oak, wheat, rain, ark, person, birds } from './noah-kit.js';

const BG = 0x2e2010;
const GROUND = 0x080604;

export function build(group) {
    const W = createScene(group, { seed: 105588677, bg: BG, fogNear: 50, fogFar: 200 });

    /* light — dusk */
    W.lights({ sky: 0x7a5a8c, gnd: 0x3a2a1a, hemi: 0.6, sun: 0xff9a50, sunI: 0.85, sunPos: [45, 12, -18] });

    W.disc([55, 22, -140], 12, 0xff9a50);
    W.disc([55, 22, -150], 20, 0xff7a30, 0.18);
    W.stars(30, 150, [0xd8c8e8, 0xc8b8d8], 0.5);
    W.disc([-60, 40, -150], 30, 0x4a3a5c, 0.25);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x030201, 0x17120c);
    W.ground(260, 95, 0, 60, 0x080604, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x070503, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x040302), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x040302), [0, -0.05, -14.6]);

    /* temple: colonnade and glowing doorway */
    const templeG = W.grp(group, [0, 0, -46], { name: 'temple', r: [0, -0.07, 0] });
    temple(W, templeG, 0, 0, 0, 1.1, { stone: 0x16120b, trim: 0x20160b });
    W.backdrop(templeG);

    /* trees: broadleaf shade */
    oak(W, group, 32.7, 0, -57.5, 1.03, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 73.7, 0, -27.3, 1.36, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 1.4, 0, -36.1, 1.29, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -34.1, 0, -29.2, 1.36, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });

    /* fields: standing grain to the horizon */
    wheat(W, group, 0, 34, 220, 110, { h: 2.1, stalk: 0x332312, head: 0x3a2814 });

    /* storm: rain sheets across the whole frame */
    rain(W, group, 900, 230, 65, 16);

    /* hero: the ark riding the flood */
    ark(W, group, 0, 0.2, 0, 1.0, { ry: 0.25 });

    /* hero: the ark */
    ark(W, group, 0, 0.2, 0, 1.1, { ry: 0.2 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x2e2010, ry: -0.59, s: 1.12 });

    /* birds: slow circles high above */
    birds(W, group, 8, 55, { y: 26 });

    return W.finish();
}

export default { build };
