/**
 * Forty Days
 * ----------
 * The rain falls forty days and forty nights, and the waters rise, and the ark floats on the face of the waters. Stage: the ark in a great sea of rain, the water over the hills, the animals in the dark below; a world of water, the rain never stopping, a lamp in the hold.
 *
 * Palette 0x061430 → 0x020810 · light: flood · hero: ark
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./noah-kit.js.
 */

import { THREE, createScene, water, rain, ark, person } from './noah-kit.js';

const BG = 0x061430;
const GROUND = 0x010306;

export function build(group) {
    const W = createScene(group, { seed: 184129913, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — flood */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x000102, 0x020912);
    W.ground(260, 95, 0, 60, 0x010306, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x010305, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x010203), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x010203), [0, -0.05, -14.6]);

    /* storm: rain sheets across the whole frame */
    rain(W, group, 900, 230, 65, 16);

    /* hero: the ark riding the flood */
    ark(W, group, 0, 0.2, 0, 1.0, { ry: 0.25 });

    /* hero: the ark */
    ark(W, group, 0, 0.2, 0, 1.1, { ry: 0.2 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x061430, ry: 0.53, s: 1.18 });

    return W.finish();
}

export default { build };
