/**
 * The Door Shuts
 * --------------
 * The Lord shuts the door of the ark, and the fountains of the deep break up, and the windows of heaven are opened. Stage: the great door closing in a darkening sky, a family inside, the first rain beginning; a world shut in, a world washed out.
 *
 * Palette 0x101828 → 0x060c18 · light: storm · hero: ark
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./noah-kit.js.
 */

import { THREE, createScene, house, rain, ark, person } from './noah-kit.js';

const BG = 0x101828;
const GROUND = 0x020408;

export function build(group) {
    const W = createScene(group, { seed: 2357968163, bg: BG, fogNear: 40, fogFar: 160 });

    /* light — storm */
    W.lights({ sky: 0x4a5a6c, gnd: 0x2a3238, hemi: 0.55, sun: 0xa8bcc8, sunI: 0.6, sunPos: [-30, 40, 20] });

    const clouds = W.grp(group, [0, 0, 0], { name: 'storm_clouds' });
    [[-50, 36, -110, 34], [0, 44, -130, 40], [55, 38, -115, 30], [-95, 40, -120, 28]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0x2a3238, { opacity: 0.9 }), [x, y, z], { s: [s, s * 0.3, s * 0.6] });
    });
    W.backdrop(clouds);
    W.point(0xbfd4f0, 4.0, 220, -22, 30, -40, 0.85);  // lightning flicker

    /* ground */
    W.ground(260, 260, 0, 0, 0x020408, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* house: mud-brick walls, flat roof, door */
    house(W, group, -19, 0, -19, 1.0 + W.r() * 0.3, { mud: 0x060b17 });
    house(W, group, -29, 0, -16, 0.8 + W.r() * 0.3, { mud: 0x060c18 });

    /* storm: rain sheets across the whole frame */
    rain(W, group, 900, 230, 65, 16);

    /* hero: the ark riding the flood */
    ark(W, group, 0, 0.2, 0, 1.0, { ry: 0.25 });

    /* hero: the ark */
    ark(W, group, 0, 0.2, 0, 1.1, { ry: 0.2 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x101828, ry: -0.02, s: 1.19 });

    return W.finish();
}

export default { build };
