/**
 * Goshen
 * ----------
 * Jacob and all his household settle in Goshen, the best of the land, and Joseph provides for them all. Stage: a green delta at dawn, a family arriving with flocks, the governor's chariot waiting, a father and son falling into each other's arms; the best of the land, in the years of famine.
 *
 * Palette 0x2d1a0e → 0x060402 · light: dawn · hero: chariot
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./joseph-kit.js.
 */

import { THREE, createScene, chariot, person } from './joseph-kit.js';

const BG = 0x2d1a0e;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 2436054230, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dawn */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-58, 30, -145], 9, 0xffd9a0);
    W.disc([-58, 30, -155], 16, 0xffb060, 0.22);
    W.stars(60, 150, [0xcfd8e8, 0xbfd0e0], 0.55);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-60, 34, -120, 24], [10, 40, -135, 30], [70, 33, -125, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xd8c8b8, { opacity: 0.5 }), [x, y, z], { s: [s, s * 0.24, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* chariot: gold-trimmed cab and spoked wheels */
    chariot(W, group, -4.1, 0, -5.0, 1.1, { ry: -0.50, gold: 0x1b1008 });

    /* hero: the chariot */
    chariot(W, group, 0, 0, 0, 1.25, { ry: 0.3, gold: 0x1b1008 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x2d1a0e, ry: -0.18, s: 1.07 });
    person(W, group, [4.5, 0, 6], { robe: 0x060402, ry: 0.31, s: 1.18 });

    return W.finish();
}

export default { build };
