/**
 * Exile and the Table
 * -------------------
 * Daniel and his friends, carried to Babylon, refuse the king's food and ask for ten days of vegetables and water. Stage: a Babylonian court cafeteria in torchlight, trays of rich food beside a humble plate of pulses; four resolute youths; jewelled walls, shadowed arcades.
 *
 * Palette 0x5c4033 → 0x2b1d0c · light: dusk · hero: water
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./daniel-kit.js.
 */

import { THREE, createScene, water, cityGate, house, column, throne, rock, person, birds } from './daniel-kit.js';

const BG = 0x5c4033;
const GROUND = 0x1a0e06;

export function build(group) {
    const W = createScene(group, { seed: 2857010228, bg: BG, fogNear: 50, fogFar: 200 });

    /* light — dusk */
    W.lights({ sky: 0x7a5a8c, gnd: 0x3a2a1a, hemi: 0.6, sun: 0xff9a50, sunI: 0.85, sunPos: [45, 12, -18] });

    W.disc([55, 22, -140], 12, 0xff9a50);
    W.disc([55, 22, -150], 20, 0xff7a30, 0.18);
    W.stars(30, 150, [0xd8c8e8, 0xc8b8d8], 0.5);
    W.disc([-60, 40, -150], 30, 0x4a3a5c, 0.25);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x090502, 0x31210e);
    W.ground(260, 95, 0, 60, 0x1a0e06, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x160c05, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x0e0803), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x0e0803), [0, -0.05, -14.6]);

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [-8, 0, -58], { name: 'city', r: [0, -0.09, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x2d1e0d, trim: 0x150b05 });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x291c0b });
    }
    W.backdrop(city);

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x2e1f0d, { band: 0x453026 });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x3c2a21 });

    /* hero: the water — a focal stone in the flow */
    rock(W, group, 0, 0, 11, 1.7, 0x170d05);

    /* figures */
    person(W, group, [-5, 0, 16], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: -0.27, s: 1.12 });
    person(W, group, [4.5, 0, 17], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.62, s: 1.14 });

    /* birds: slow circles high above */
    birds(W, group, 6, 55, { y: 26 });

    return W.finish();
}

export default { build };
