/**
 * The Great Statue
 * ----------------
 * Nebuchadnezzar dreams of a colossal statue — gold head, silver chest, bronze belly, iron legs, feet of clay — shattered by a stone that becomes a mountain. Stage: the dream image towering in a night sky over Babylon, metals graded top to bottom, a stone striking the feet; cold moonlight and a blast of light as it falls.
 *
 * Palette 0x3d1c08 → 0x1e0f0a · light: dream · hero: pillar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./daniel-kit.js.
 */

import { THREE, createScene, cityGate, house, pillar, person, birds } from './daniel-kit.js';

const BG = 0x3d1c08;
const GROUND = 0x0d0705;

export function build(group) {
    const W = createScene(group, { seed: 495599504, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dream */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x0d0705, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0x0a0504), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [12, 0, -58], { name: 'city', r: [0, 0.18, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x20100b, trim: 0x0a0604 });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x1d0e0a });
    }
    W.backdrop(city);

    /* hero: the standing stone */
    pillar(W, group, 0, 0, 0, 1.15, { stone: 0x1e0f0a });
    W.disc([0, 6, -12], 5, 0x4f240a, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x3d1c08, ry: 0.70, s: 1.16 });

    /* birds: slow circles high above */
    birds(W, group, 6, 55, { y: 26 });

    return W.finish();
}

export default { build };
