/**
 * The Furnace
 * -----------
 * Shadrach, Meshach and Abednego are bound and cast into the blazing furnace, where a fourth figure like a son of the gods walks with them. Stage: a roaring furnace mouth on a Babylonian plain, soldiers flinging bound youths into white heat; inside, four figures unharmed; furnace orange, king and court watching from shaded terraces.
 *
 * Palette 0x8b2500 → 0x3d1200 · light: fire · hero: pillar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./daniel-kit.js.
 */

import { THREE, createScene, column, throne, pillar, person } from './daniel-kit.js';

const BG = 0x8b2500;
const GROUND = 0x1a0700;

export function build(group) {
    const W = createScene(group, { seed: 3683894660, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — fire */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x1a0700, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x421300, { band: 0x681c00 });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x5a1800 });

    /* hero: the standing stone */
    pillar(W, group, 0, 0, 0, 1.15, { stone: 0x3d1200 });
    W.disc([0, 6, -12], 5, 0xb53000, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, bend: 0.02, ry: -0.04, s: 1.06 });
    person(W, group, [4.5, 0, 6], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, bend: 0.02, ry: 0.15, s: 1.12 });

    return W.finish();
}

export default { build };
