/**
 * The Proud King
 * --------------
 * Nebuchadnezzar is driven from human society, eating grass like an ox until his reason returns. Stage: a royal garden gone wild, the king grown long-haired and wild-eyed among stalks and dew; gold and madness fading to humble green; a shaft of light as his sanity is restored.
 *
 * Palette 0x2b1220 → 0x160a14 · light: constellation · hero: pillar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./daniel-kit.js.
 */

import { THREE, createScene, cityGate, house, column, throne, oak, tree, well, pillar, person, birds } from './daniel-kit.js';

const BG = 0x2b1220;
const GROUND = 0x090510;

export function build(group) {
    const W = createScene(group, { seed: 3419723496, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — constellation */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x090510, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [-20, 0, -58], { name: 'city', r: [0, 0.07, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x170b15, trim: 0x07040d });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x150a13 });
    }
    W.backdrop(city);

    /* palace: columns, banners and the throne */
    for (let i = -2; i <= 2; i++) column(W, group, i * 8, 0, -30, 11, 1.3, 0x180b16, { band: 0x200e18 });
    throne(W, group, 0, 0, -24, 1.4, { gold: 0x1c0c15 });

    /* trees: broadleaf shade */
    oak(W, group, -34.9, 0, -11.3, 0.97, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 39.5, 0, -51.7, 1.31, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 14.4, 0, -8.0, 1.08, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    tree(W, group, -17.3, 0, -11.6, 1.1);

    /* garden: shade trees around a well */
    well(W, group, 1.9, 0, 2.5, 1.1);

    /* hero: the standing stone */
    pillar(W, group, 0, 0, 0, 1.15, { stone: 0x160a14 });
    W.disc([0, 6, -12], 5, 0x38172a, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0xe8dcc0, head: 'crown', collar: 0xe0b040, ry: 0.12, s: 1.14 });

    /* birds: slow circles high above */
    birds(W, group, 6, 55, { y: 26 });

    return W.finish();
}

export default { build };
