// Character preset data for character_head_generator.html
// Edit this file to add, remove, or tweak characters.
// Loaded via a <script> tag (not fetch) so it works when the HTML
// file is opened directly by double-clicking, with no local server
// needed (browsers block fetch() of local files from file:// pages).

const CHARACTER_PRESETS_DATA = {

  // ============================================================
  // EXISTING CHARACTER PRESETS
  // ============================================================

  "senior_scribe": {
    "name": "Senior Scribe",
    "noseScale": 0.95,
    "noseShape": "button",
    "eyeShape": "almond",
    "eyeSpacing": 0.95,
    "eyebrowStyle": "arched",
    "mouthStyle": "neutral",
    "hairStyle": "receding",
    "beardStyle": "long",
    "hatStyle": "turban",
    "clothingType": "priestly_ephod",
    "faceShape": "square",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 0.95,
    "earShape": "elfin",
    "headSize": 1.0,
    "hairSize": 0.95,
    "hatSize": 1.06,
    "hatMatchHair": false,
    "dualStripe": true,
    "colorInner": "#e8e0cf",
    "colorOuter": "#3b2342",
    "colorCloak": "#241830",
    "colorAccent": "#2e4560",
    "colorGarment2": "#d4af37",
    "colorSkin": "#b58052",
    "colorHair": "#8a8a8a",
    "colorEye": "#42352b",
    "colorLip": "#8f5245"
  },

  "thomas": {
    "name": "Thomas the Twin",
    "noseScale": 0.9,
    "noseShape": "button",
    "eyeShape": "narrow",
    "eyeSpacing": 1.05,
    "eyebrowStyle": "thin",
    "mouthStyle": "neutral",
    "hairStyle": "short",
    "beardStyle": "short",
    "hatStyle": "none",
    "clothingType": "tunic",
    "faceShape": "oval",
    "foreheadHeight": "low",
    "chinShape": "square",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.0,
    "hairSize": 1.03,
    "hatSize": 1.0,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#3f382f",
    "colorOuter": "#28241e",
    "colorCloak": "#1a1815",
    "colorAccent": "#3b3831",
    "colorGarment2": "#7a6a4a",
    "colorSkin": "#c58c5c",
    "colorHair": "#2a1e15",
    "colorEye": "#4a3b32",
    "colorLip": "#8f5245"
  },

  // ------------------------------------------------------------
  // ... KEEP YOUR OTHER EXISTING PRESETS HERE ...
  // ------------------------------------------------------------


  // ============================================================
  // ELIJAH STORY
  // 1 Kings 17 – 2 Kings 2
  // ============================================================

  "elijah": {
    "name": "Elijah",
    "noseScale": 1.05,
    "noseShape": "straight",
    "eyeShape": "almond",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "thick",
    "mouthStyle": "neutral",
    "hairStyle": "wild",
    "beardStyle": "long",
    "hatStyle": "none",
    "clothingType": "prophet_rough",
    "faceShape": "oval",
    "foreheadHeight": "medium",
    "chinShape": "square",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.05,
    "hairSize": 1.25,
    "hatSize": 1.0,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#4a4035",
    "colorOuter": "#29231d",
    "colorCloak": "#171411",
    "colorAccent": "#6b5138",
    "colorGarment2": "#806747",
    "colorSkin": "#b98053",
    "colorHair": "#211811",
    "colorEye": "#3b2a20",
    "colorLip": "#92554a"
  },

  "ahab": {
    "name": "King Ahab",
    "noseScale": 1.05,
    "noseShape": "wide",
    "eyeShape": "narrow",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "straight",
    "mouthStyle": "frown",
    "hairStyle": "receding",
    "beardStyle": "medium",
    "hatStyle": "crown",
    "clothingType": "royal_robe",
    "faceShape": "oval",
    "foreheadHeight": "high",
    "chinShape": "square",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.08,
    "hairSize": 0.9,
    "hatSize": 1.12,
    "hatMatchHair": false,
    "dualStripe": true,
    "colorInner": "#e8dfc9",
    "colorOuter": "#51372c",
    "colorCloak": "#261925",
    "colorAccent": "#8c672d",
    "colorGarment2": "#d4af37",
    "colorSkin": "#bd8759",
    "colorHair": "#4a2f20",
    "colorEye": "#3d2a20",
    "colorLip": "#92554a"
  },

  "jezebel": {
    "name": "Queen Jezebel",
    "noseScale": 0.95,
    "noseShape": "straight",
    "eyeShape": "hooded",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "arched",
    "mouthStyle": "smirk",
    "hairStyle": "flowing",
    "beardStyle": "none",
    "hatStyle": "headdress",
    "clothingType": "royal_robe",
    "faceShape": "thin",
    "foreheadHeight": "high",
    "chinShape": "pointed",
    "earSize": 0.7,
    "earShape": "round",
    "headSize": 0.92,
    "hairSize": 1.3,
    "hatSize": 1.08,
    "hatMatchHair": false,
    "dualStripe": true,
    "colorInner": "#eee4d0",
    "colorOuter": "#45243f",
    "colorCloak": "#241329",
    "colorAccent": "#7b345e",
    "colorGarment2": "#d4af37",
    "colorSkin": "#d1a078",
    "colorHair": "#21140f",
    "colorEye": "#302018",
    "colorLip": "#9d4d5b"
  },

  "obadiah": {
    "name": "Obadiah",
    "noseScale": 1.0,
    "noseShape": "straight",
    "eyeShape": "hooded",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "arched",
    "mouthStyle": "neutral",
    "hairStyle": "receding",
    "beardStyle": "medium",
    "hatStyle": "hood",
    "clothingType": "layered_robe",
    "faceShape": "oval",
    "foreheadHeight": "high",
    "chinShape": "rounded",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.0,
    "hairSize": 0.85,
    "hatSize": 1.05,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#625344",
    "colorOuter": "#39302a",
    "colorCloak": "#211c18",
    "colorAccent": "#4d493e",
    "colorGarment2": "#7a6a4a",
    "colorSkin": "#c18b5c",
    "colorHair": "#756e65",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "widow_zarephath": {
    "name": "Widow of Zarephath",
    "noseScale": 1.0,
    "noseShape": "wide",
    "eyeShape": "hooded",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "furrowed",
    "mouthStyle": "frown",
    "hairStyle": "tied_back",
    "beardStyle": "none",
    "hatStyle": "headscarf",
    "clothingType": "peasant_rags",
    "faceShape": "heart",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 0.65,
    "earShape": "round",
    "headSize": 0.88,
    "hairSize": 1.1,
    "hatSize": 1.08,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#65594b",
    "colorOuter": "#40382f",
    "colorCloak": "#27221d",
    "colorAccent": "#6a5842",
    "colorGarment2": "#8a7650",
    "colorSkin": "#c89468",
    "colorHair": "#241912",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "widows_son": {
    "name": "Widow's Son",
    "noseScale": 0.9,
    "noseShape": "button",
    "eyeShape": "round",
    "eyeSpacing": 1.05,
    "eyebrowStyle": "straight",
    "mouthStyle": "neutral",
    "hairStyle": "short",
    "beardStyle": "none",
    "hatStyle": "none",
    "clothingType": "peasant_rags",
    "faceShape": "round",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 0.8,
    "earShape": "round",
    "headSize": 0.82,
    "hairSize": 1.0,
    "hatSize": 1.0,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#51483d",
    "colorOuter": "#342e28",
    "colorCloak": "#201c18",
    "colorAccent": "#4a4035",
    "colorGarment2": "#74634a",
    "colorSkin": "#c38d60",
    "colorHair": "#2b1e16",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "prophet_of_baal": {
    "name": "Prophet of Baal",
    "noseScale": 1.05,
    "noseShape": "aquiline",
    "eyeShape": "narrow",
    "eyeSpacing": 0.95,
    "eyebrowStyle": "thick",
    "mouthStyle": "frown",
    "hairStyle": "curly",
    "beardStyle": "full_round",
    "hatStyle": "turban",
    "clothingType": "layered_robe",
    "faceShape": "square",
    "foreheadHeight": "medium",
    "chinShape": "square",
    "earSize": 1.1,
    "earShape": "round",
    "headSize": 1.0,
    "hairSize": 1.15,
    "hatSize": 1.08,
    "hatMatchHair": false,
    "dualStripe": true,
    "colorInner": "#3b3030",
    "colorOuter": "#211d2c",
    "colorCloak": "#120f1b",
    "colorAccent": "#5f2632",
    "colorGarment2": "#8a6b34",
    "colorSkin": "#b67d50",
    "colorHair": "#17110c",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "elijah_servant": {
    "name": "Elijah's Servant",
    "noseScale": 0.95,
    "noseShape": "straight",
    "eyeShape": "almond",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "straight",
    "mouthStyle": "neutral",
    "hairStyle": "short",
    "beardStyle": "stubble",
    "hatStyle": "hood",
    "clothingType": "tunic",
    "faceShape": "oval",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 0.95,
    "hairSize": 1.0,
    "hatSize": 1.02,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#4c4237",
    "colorOuter": "#302a24",
    "colorCloak": "#1c1915",
    "colorAccent": "#4c4639",
    "colorGarment2": "#7a6a4a",
    "colorSkin": "#bf895b",
    "colorHair": "#2b2119",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "angel_of_the_lord": {
    "name": "Angel of the Lord",
    "noseScale": 0.95,
    "noseShape": "straight",
    "eyeShape": "round",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "arched",
    "mouthStyle": "neutral",
    "hairStyle": "flowing",
    "beardStyle": "none",
    "hatStyle": "none",
    "clothingType": "layered_robe",
    "faceShape": "oval",
    "foreheadHeight": "high",
    "chinShape": "rounded",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.0,
    "hairSize": 1.25,
    "hatSize": 1.0,
    "hatMatchHair": false,
    "dualStripe": true,
    "colorInner": "#f0eadb",
    "colorOuter": "#d7c7a5",
    "colorCloak": "#8b7c60",
    "colorAccent": "#d4af37",
    "colorGarment2": "#f3df91",
    "colorSkin": "#d8b088",
    "colorHair": "#d8d3c8",
    "colorEye": "#6a5a43",
    "colorLip": "#a85d5d"
  },

  "ahaziah": {
    "name": "King Ahaziah",
    "noseScale": 1.0,
    "noseShape": "wide",
    "eyeShape": "hooded",
    "eyeSpacing": 1.05,
    "eyebrowStyle": "furrowed",
    "mouthStyle": "frown",
    "hairStyle": "short",
    "beardStyle": "stubble",
    "hatStyle": "turban",
    "clothingType": "layered_robe",
    "faceShape": "oval",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.05,
    "hairSize": 1.0,
    "hatSize": 1.04,
    "hatMatchHair": false,
    "dualStripe": true,
    "colorInner": "#dfd1ba",
    "colorOuter": "#49304b",
    "colorCloak": "#21172b",
    "colorAccent": "#8a6a32",
    "colorGarment2": "#d4af37",
    "colorSkin": "#b98458",
    "colorHair": "#332319",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "naboth": {
    "name": "Naboth",
    "noseScale": 1.0,
    "noseShape": "straight",
    "eyeShape": "almond",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "arched",
    "mouthStyle": "neutral",
    "hairStyle": "wavy",
    "beardStyle": "medium",
    "hatStyle": "none",
    "clothingType": "tunic",
    "faceShape": "oval",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.0,
    "hairSize": 1.0,
    "hatSize": 1.0,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#5c4c3d",
    "colorOuter": "#393129",
    "colorCloak": "#211d18",
    "colorAccent": "#4e473b",
    "colorGarment2": "#806c4b",
    "colorSkin": "#c28d60",
    "colorHair": "#38261a",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "captain_of_fifty": {
    "name": "Captain of Fifty",
    "noseScale": 1.0,
    "noseShape": "straight",
    "eyeShape": "narrow",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "thick",
    "mouthStyle": "frown",
    "hairStyle": "short",
    "beardStyle": "stubble",
    "hatStyle": "helmet",
    "clothingType": "military_lorica",
    "faceShape": "square",
    "foreheadHeight": "medium",
    "chinShape": "square",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.05,
    "hairSize": 1.0,
    "hatSize": 1.05,
    "hatMatchHair": false,
    "dualStripe": true,
    "colorInner": "#4a4438",
    "colorOuter": "#33352f",
    "colorCloak": "#211f1b",
    "colorAccent": "#665b3f",
    "colorGarment2": "#8a7a5a",
    "colorSkin": "#b77f52",
    "colorHair": "#241a13",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "messenger_of_ahaziah": {
    "name": "Messenger of Ahaziah",
    "noseScale": 1.0,
    "noseShape": "straight",
    "eyeShape": "almond",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "straight",
    "mouthStyle": "neutral",
    "hairStyle": "short",
    "beardStyle": "stubble",
    "hatStyle": "hood",
    "clothingType": "tunic",
    "faceShape": "oval",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.0,
    "hairSize": 1.0,
    "hatSize": 1.02,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#4c4438",
    "colorOuter": "#302b25",
    "colorCloak": "#1b1815",
    "colorAccent": "#4d4638",
    "colorGarment2": "#7a6a4a",
    "colorSkin": "#c28d60",
    "colorHair": "#302117",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  },

  "elisha": {
    "name": "Elisha",
    "noseScale": 1.0,
    "noseShape": "straight",
    "eyeShape": "almond",
    "eyeSpacing": 1.0,
    "eyebrowStyle": "arched",
    "mouthStyle": "neutral",
    "hairStyle": "short",
    "beardStyle": "stubble",
    "hatStyle": "none",
    "clothingType": "tunic",
    "faceShape": "oval",
    "foreheadHeight": "medium",
    "chinShape": "rounded",
    "earSize": 1.0,
    "earShape": "round",
    "headSize": 1.0,
    "hairSize": 1.0,
    "hatSize": 1.0,
    "hatMatchHair": false,
    "dualStripe": false,
    "colorInner": "#4b4339",
    "colorOuter": "#302a24",
    "colorCloak": "#1b1815",
    "colorAccent": "#4c4639",
    "colorGarment2": "#7a6a4a",
    "colorSkin": "#bd895b",
    "colorHair": "#241a13",
    "colorEye": "#463329",
    "colorLip": "#92554a"
  }
};


// ============================================================
// POPULATE PRESET DROPDOWN
// ============================================================
//
// Dynamically builds the characterPresetSelect options from
// CHARACTER_PRESETS_DATA so the dropdown always reflects the
// actual available presets.
//
// ============================================================

(function populatePresetDropdown() {

  const select = document.getElementById("characterPresetSelect");

  if (!select) return;

  const groups = {
    "Scribes & Observers": ["senior_scribe", "thomas"],
    "Elijah — Kings & Prophets": [
      "elijah",
      "ahab",
      "jezebel",
      "obadiah",
      "widow_zarephath",
      "widows_son",
      "prophet_of_baal",
      "elijah_servant",
      "angel_of_the_lord",
      "ahaziah",
      "naboth",
      "captain_of_fifty",
      "messenger_of_ahaziah",
      "elisha"
    ]
  };

  const groupedKeys = new Set(Object.values(groups).flat());
  const ungroupedKeys = Object.keys(CHARACTER_PRESETS_DATA).filter(k => !groupedKeys.has(k));
  if (ungroupedKeys.length > 0) {
    groups["Other"] = ungroupedKeys;
  }

  Object.entries(groups).forEach(([label, keys]) => {
    const group = document.createElement("optgroup");
    group.label = label;
    keys.forEach(key => {
      if (!CHARACTER_PRESETS_DATA[key]) return;
      const option = document.createElement("option");
      option.value = key;
      option.textContent = CHARACTER_PRESETS_DATA[key].name;
      group.appendChild(option);
    });
    if (group.children.length > 0) {
      select.appendChild(group);
    }
  });

})();