/**
 * Purim
 * ----------
 * The Jews feast and send gifts, and the days of Purim are fixed — a feast of reversal. Stage: a city street in festival light, tables of food, children in costume, a scroll unrolled; warm lanterns, the sound of celebration.
 *
 * Palette 0x2d1a0e → 0x060402 · light: dawn · hero: scroll
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./esther-kit.js.
 */

import { THREE, createScene, cityGate, house, scroll, person, birds } from './esther-kit.js';

const BG = 0x2d1a0e;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 3996553353, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dawn */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-58, 30, -145], 9, 0xffd9a0);
    W.disc([-58, 30, -155], 16, 0xffb060, 0.22);
    W.stars(60, 150, [0xcfd8e8, 0xbfd0e0], 0.55);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-60, 34, -120, 24], [10, 40, -135, 30], [70, 33, -125, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xd8c8b8, { opacity: 0.5 }), [x, y, z], { s: [s, s * 0.24, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [-21, 0, -58], { name: 'city', r: [0, -0.13, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x060402, trim: 0x050302 });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x060402 });
    }
    W.backdrop(city);

    /* hero: the scroll */
    scroll(W, group, 0, 0.9, 0, 1.2, { ry: 0.5 });
    W.disc([0, 4, -10], 4, 0x3b2212, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x2d1a0e, ry: -0.23, s: 1.04 });

    /* birds: slow circles high above */
    birds(W, group, 8, 55, { y: 26 });

    return W.finish();
}

export default { build };
