/**
 * Together
 * ----------
 * The animals are brought to Adam for naming, and from his side God forms the woman. Stage: a shaded clearing at dusk, creatures gathering in pairs, the man reaching toward the new companion; rose-gold evening light, a sense of completion.
 *
 * Palette 0x2b1220 → 0x160a14 · light: dream · hero: pillar
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./adam-kit.js.
 */

import { THREE, createScene, pillar, person, crowd } from './adam-kit.js';

const BG = 0x2b1220;
const GROUND = 0x0d0709;

export function build(group) {
    const W = createScene(group, { seed: 2467640312, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dream */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x0d0709, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hero: the standing stone */
    pillar(W, group, 0, 0, 0, 1.15, { stone: 0x160a14 });
    W.disc([0, 6, -12], 5, 0x38172a, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x2b1220, ry: -0.26, s: 1.20 });
    person(W, group, [4.5, 0, 6], { robe: 0x160a14, ry: -0.40, s: 1.08 });
    /* crowd: the people of the story */
    crowd(W, group, 0, 16, 24, 70, 44, [0x2b1220, 0x160a14, 0x0d0709, 0x8a6a44, 0x6a4a30, 0xc8b088]);

    return W.finish();
}

export default { build };
