/**
 * The Garden
 * ----------
 * God plants Eden in the east and sets the man among every tree pleasant to the eye, with the river dividing into four heads. Stage: a lush riverside garden, pomegranate and fig, gold and green; the man walking among the trees, lion and lamb at the water's edge; soft diffused light through leaves.
 *
 * Palette 0x2b1d0c → 0x1a0e06 · light: dusk · hero: lion
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./adam-kit.js.
 */

import { THREE, createScene, water, oak, tree, well, sheep, lion, person, birds } from './adam-kit.js';

const BG = 0x2b1d0c;
const GROUND = 0x0d0705;

export function build(group) {
    const W = createScene(group, { seed: 2063038897, bg: BG, fogNear: 50, fogFar: 200 });

    /* light — dusk */
    W.lights({ sky: 0x7a5a8c, gnd: 0x3a2a1a, hemi: 0.6, sun: 0xff9a50, sunI: 0.85, sunPos: [45, 12, -18] });

    W.disc([55, 22, -140], 12, 0xff9a50);
    W.disc([55, 22, -150], 20, 0xff7a30, 0.18);
    W.stars(30, 150, [0xd8c8e8, 0xc8b8d8], 0.5);
    W.disc([-60, 40, -150], 30, 0x4a3a5c, 0.25);

    /* river: animated water between grassy banks */
    water(W, group, 260, 26, -0.4, 0x050202, 0x1e1007);
    W.ground(260, 95, 0, 60, 0x0d0705, { amp: 0.5, j: 0.3, flat: 24, fz: 54 });
    W.ground(260, 95, 0, -64, 0x0b0604, { amp: 0.6, j: 0.3, flat: 24, fz: -58 });
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x070403), [0, -0.05, 12.6]);
    W.add(group, W.G('box', 260, 0.3, 4), W.mat(0x070403), [0, -0.05, -14.6]);

    /* trees: broadleaf shade */
    oak(W, group, 49.3, 0, -3.8, 1.38, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -13.4, 0, -5.6, 0.95, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -52.4, 0, -0.1, 1.12, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -50.6, 0, -42.8, 1.27, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -11.9, 0, -50.1, 1.37, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    tree(W, group, -16.9, 0, -0.2, 1.1);

    /* garden: shade trees around a well */
    well(W, group, 3.5, 0, 6.3, 1.1);

    /* flock: sheep grazing */
    sheep(W, group, 9.4, 0, 9.4, W.r() * 6, 0.91);
    sheep(W, group, -12.8, 0, 0.5, W.r() * 6, 0.85);
    sheep(W, group, 11.0, 0, -8.4, W.r() * 6, 0.92);
    sheep(W, group, -0.3, 0, -11.3, W.r() * 6, 1.17);
    sheep(W, group, 1.8, 0, -9.8, W.r() * 6, 0.96);
    sheep(W, group, 0.7, 0, -1.2, W.r() * 6, 1.00);
    sheep(W, group, 15.5, 0, -7.7, W.r() * 6, 1.05);
    /* lion: the danger in the scene */
    lion(W, group, 1.1, 0, 4.3, 1.1, { ry: 0.48 });

    /* hero: the lion */
    lion(W, group, 0, 0, 11, 1.35, { ry: 0.4 });
    W.disc([0, 5, -1], 6, 0x382610, 0.3);

    /* figures */
    person(W, group, [-5, 0, 16], { robe: 0x2b1d0c, bend: 0.2, armR: [0.35, 0.1], armL: [-0.35, -0.1], ry: -0.65, s: 1.10 });

    /* birds: slow circles high above */
    birds(W, group, 7, 55, { y: 26 });

    return W.finish();
}

export default { build };
