/**
 * Hiding
 * ----------
 * They hear the Lord walking in the garden at the cool of the day and hide among the trees. Stage: tall grasses and fig leaves at evening, two figures crouched, guilty and bare; a searching shaft of light moving through the grove.
 *
 * Palette 0x0d1b2a → 0x061224 · light: stars · hero: tree
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./adam-kit.js.
 */

import { THREE, createScene, oak, tree, well, person, birds } from './adam-kit.js';

const BG = 0x0d1b2a;
const GROUND = 0x030b18;

export function build(group) {
    const W = createScene(group, { seed: 4070363391, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — stars */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-30, 70, -150], 10, 0xfff8e8);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-40, 44, -125, 26], [30, 50, -135, 32], [85, 42, -120, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xf0f4f8, { opacity: 0.75 }), [x, y, z], { s: [s, s * 0.22, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x030b18, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* trees: broadleaf shade */
    oak(W, group, 20.9, 0, -47.2, 1.34, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 71.5, 0, -58.4, 1.22, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 51.0, 0, -7.4, 1.05, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, 55.5, 0, -43.9, 1.05, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    oak(W, group, -0.7, 0, 3.7, 1.12, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    tree(W, group, 18.9, 0, 2.3, 1.1);

    /* garden: shade trees around a well */
    well(W, group, 2.9, 0, 4.0, 1.1);

    /* hero: the great tree */
    oak(W, group, 0, 0, 0, 1.7, { leaf: 0x4f8a2e, leaf2: 0x5fa036 });
    W.disc([0, 8, -16], 9, 0x112337, 0.25);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x0d1b2a, bend: 0.2, armR: [0.35, 0.1], armL: [-0.35, -0.1], ry: -0.03, s: 1.03 });

    /* birds: slow circles high above */
    birds(W, group, 6, 55, { y: 26 });

    return W.finish();
}

export default { build };
