// Canonical character inventory for Moses. Generated from __docs/moses-design-source-of-truth.md.
const CHARACTER_PRESETS_META = {
  "story": "Moses",
  "defaultPreset": "moses_young",
  "groupLabel": "Moses characters"
};
const STORY_CHARACTER_BASE = {
  "noseScale": 1,
  "noseShape": "straight",
  "eyeShape": "almond",
  "eyeSpacing": 1,
  "eyebrowStyle": "arched",
  "mouthStyle": "neutral",
  "hairStyle": "wavy",
  "beardStyle": "short",
  "hatStyle": "none",
  "clothingType": "tunic",
  "faceShape": "oval",
  "foreheadHeight": "medium",
  "chinShape": "rounded",
  "earSize": 1,
  "earShape": "round",
  "headSize": 1,
  "hairSize": 1,
  "hatSize": 1,
  "hatMatchHair": false,
  "dualStripe": false,
  "colorInner": "#c7a56a",
  "colorOuter": "#6f4c2d",
  "colorCloak": "#493321",
  "colorAccent": "#b78a3d",
  "colorGarment2": "#ddd0ad",
  "colorSkin": "#b9825d",
  "colorHair": "#2a1d16",
  "colorEye": "#3d2d24",
  "colorLip": "#985e50"
};
const storyPreset=(name,overrides={})=>({...STORY_CHARACTER_BASE,name,...overrides});
const CHARACTER_PRESETS_DATA = {
  "moses_young": storyPreset("Moses Young", {}),
  "moses": storyPreset("Moses", {"noseShape":"aquiline","eyebrowStyle":"thick"}),
  "aaron": storyPreset("Aaron", {"faceShape":"square","chinShape":"square","colorSkin":"#9d6748"}),
  "miriam": storyPreset("Miriam", {"beardStyle":"none","hairStyle":"flowing","hatStyle":"headscarf","colorOuter":"#6d3f48"}),
  "pharaoh": storyPreset("Pharaoh", {"clothingType":"layered_robe","colorOuter":"#395b7a","colorAccent":"#d4aa45","dualStripe":true}),
  "pharaohs_daughter": storyPreset("Pharaoh’s Daughter", {"beardStyle":"none","hairStyle":"braids","hatStyle":"headscarf","clothingType":"layered_robe","colorOuter":"#395b7a","colorAccent":"#d4aa45","dualStripe":true,"noseShape":"aquiline","eyebrowStyle":"thick"}),
  "zipporah": storyPreset("Zipporah", {"beardStyle":"none","hairStyle":"tied_back","hatStyle":"headscarf","faceShape":"square","chinShape":"square","colorSkin":"#9d6748"}),
  "jethro": storyPreset("Jethro", {"hairStyle":"curly","colorOuter":"#6d3f48"}),
  "joshua": storyPreset("Joshua", {}),
  "caleb": storyPreset("Caleb", {"noseShape":"aquiline","eyebrowStyle":"thick"}),
  "israelite_elder": storyPreset("Israelite Elder", {"faceShape":"square","chinShape":"square","colorSkin":"#9d6748"}),
  "israelite_woman": storyPreset("Israelite Woman", {"beardStyle":"none","hairStyle":"flowing","hatStyle":"headscarf","colorOuter":"#6d3f48"}),
  "egyptian_overseer": storyPreset("Egyptian Overseer", {}),
  "korah": storyPreset("Korah", {"noseShape":"aquiline","eyebrowStyle":"thick"}),
  "balaam": storyPreset("Balaam", {"faceShape":"square","chinShape":"square","colorSkin":"#9d6748"}),
};
