/**
 * Ai
 * ----------
 * Joshua sets an ambush and takes Ai, and the people of Ai are taken captive. Stage: a ruined hill at dawn, a retreating force, an ambush in the fields, the city burning; smoke over a valley, a battle learned the hard way.
 *
 * Palette 0x1a2a14 → 0x060402 · light: ember · hero: fire
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./joshua-kit.js.
 */

import { THREE, createScene, cityGate, house, army, oak, flame, person, crowd } from './joshua-kit.js';

const BG = 0x1a2a14;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 553447253, bg: BG, fogNear: 45, fogFar: 180 });

    /* light — ember */
    W.lights({ sky: 0x3a2418, gnd: 0x1a0e08, hemi: 0.4, sun: 0xff7a30, sunI: 0.7, sunPos: [20, 26, 30] });

    W.stars(90, 150, [0xf0e0c8, 0xd8c0a0], 0.7);
    W.disc([0, 34, -150], 14, 0xff8a30, 0.12);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hills: angular ridges on the horizon */
    const hills = W.grp(group, [0, 0, 0], { name: 'hills' });
    for (let i = 0; i < 9; i++) {
        const x = -130 + i * 32 + W.rr(-8, 8);
        W.add(hills, W.G('cone', W.rr(14, 28), W.rr(10, 24), 5), W.mat(0x050302), [x, 0, -95 - W.rr(0, 25)], { r: [0, W.r() * 3, 0] });
    }
    W.backdrop(hills);

    /* city: gate, towers and houses on the far side */
    const city = W.grp(group, [13, 0, -58], { name: 'city', r: [0, 0.02, 0] });
    cityGate(W, city, 0, 0, 0, 1.15, { stone: 0x060402, trim: 0x050302 });
    for (let i = 0; i < 5; i++) {
        house(W, city, -34 + i * 17 + W.rr(-4, 4), 0, W.rr(-14, 6), 0.85 + W.r() * 0.4, { mud: 0x060402 });
    }
    W.backdrop(city);

    /* army: shields and spears in rank */
    army(W, group, -12.4, 27.7, 8, { shields: [0x111b0d, 0x050402, 0x8a7a2a, 0x3a5a8a] });

    /* hero: the burning bush */
    oak(W, group, 0, 0, 0, 0.75, { leaf: 0x3a4a20, leaf2: 0x4a5a28 });
    flame(W, group, 0, 1.4, 0, 1.0);
    W.point(0xff8a30, 2.4, 60, 0, 3, 0, 0.4);
    W.disc([0, 6, -12], 7, 0xffa050, 0.3);

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x1a2a14, ry: -0.39, s: 1.11 });
    /* crowd: the people of the story */
    crowd(W, group, 0, 16, 25, 70, 44, [0x1a2a14, 0x060402, 0x8a6a44, 0x6a4a30, 0xc8b088, 0x5a4a6a]);

    return W.finish();
}

export default { build };
