/**
 * Taken
 * ----------
 * Enoch is not, for God takes him — no grave, no death, only the road that ends in light. Stage: a hilltop road at sunrise, the figure fading into a shining mist; the city below stirring awake; a doorway of light at the horizon.
 *
 * Palette 0x2a1a10 → 0x060402 · light: dawn · hero: city
 *
 * Generated by scripts/add-shot-scenes.mjs from the act data and
 * the mood board in ../../art/. Composition follows the kit in
 * ./enoch-kit.js.
 */

import { THREE, createScene, cityGate, person, birds } from './enoch-kit.js';

const BG = 0x2a1a10;
const GROUND = 0x060402;

export function build(group) {
    const W = createScene(group, { seed: 2678827805, bg: BG, fogNear: 55, fogFar: 220 });

    /* light — dawn */
    W.lights({ sky: 0x9ab4d0, gnd: 0x5a5a52, hemi: 0.75, sun: 0xffd9a0, sunI: 0.95, sunPos: [-45, 16, 26] });

    W.disc([-58, 30, -145], 9, 0xffd9a0);
    W.disc([-58, 30, -155], 16, 0xffb060, 0.22);
    W.stars(60, 150, [0xcfd8e8, 0xbfd0e0], 0.55);
    const clouds = W.grp(group, [0, 0, 0], { name: 'cloud_bank' });
    [[-60, 34, -120, 24], [10, 40, -135, 30], [70, 33, -125, 22]].forEach(([x, y, z, s]) => {
        W.add(clouds, W.G('ico', 1, 1), W.mat(0xd8c8b8, { opacity: 0.5 }), [x, y, z], { s: [s, s * 0.24, s * 0.5] });
    });
    W.backdrop(clouds);

    /* ground */
    W.ground(260, 260, 0, 0, 0x060402, { amp: 0.6, j: 0.3, flat: 30, rise: (x, z) => Math.sin(x * 0.05) * Math.cos(z * 0.04) * 1.2 });

    /* hero: the city gate */
    cityGate(W, group, 0, 0, -8, 1.1, { stone: 0x060402, trim: 0x050302 });

    /* figures */
    person(W, group, [-5, 0, 5], { robe: 0x2a1a10, ry: -0.56, s: 1.01 });
    person(W, group, [4.5, 0, 6], { robe: 0x060402, ry: -0.52, s: 1.04 });
    person(W, group, [1, 0, -5], { robe: 0x8a6a44, ry: -0.07, s: 1.14 });

    /* birds: slow circles high above */
    birds(W, group, 6, 55, { y: 26 });

    return W.finish();
}

export default { build };
